# .github/workflows/test-rollout-pipeline.yml

name: Test | Validate Rollout Pipeline

on:
  pull_request:
    paths:
      - '.github/workflows/rollout-restart.yml'
  workflow_dispatch:

jobs:
  # =================================================================
  #  LINT WORKFLOW FILE
  # =================================================================
  lint-workflow:
    name: "🔎 Lint Workflow File"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Run Action Linter"
        uses: rhysd/actionlint-github-actions@v1
        with:
          rcfile: '.github/actionlint.yml'

  # =================================================================
  #  DRY-RUN DEPLOYMENT LOGIC
  # =================================================================
  test-deployment-logic:
    name: "🧪 Test Rollout Logic (Dry Run)"
    runs-on: ubuntu-latest
    needs: lint-workflow
    strategy:
      matrix:
        # We test the logic against a single sandbox/test cluster
        # This validates authentication and command structure
        environment_name: [ "demo", "uat", "prod" ]

    steps:
      - name: "Configure AWS Credentials for Sandbox"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.SANDBOX_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SANDBOX_AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1" # Sandbox region

      - name: "Set up Kubeconfig for Sandbox"
        uses: aws-actions/amazon-eks-set-context@v1
        with:
          cluster-name: "sandbox-cluster" # CHANGE THIS

      - name: "Dry-Run Rollout Restart"
        run: |
          # We are testing if a deployment named 'my-app-demo', 'my-app-uat', etc.
          # can be targeted in the sandbox cluster.
          DEPLOYMENT_NAME="my-app-${{ matrix.environment_name }}"
          echo "Executing dry-run for deployment ${DEPLOYMENT_NAME}..."
          kubectl rollout restart deployment/${DEPLOYMENT_NAME} --dry-run=client -o yaml